In [ ]:
import pandas as pd
data = pd.read_csv("data\missingData.csv")
copy_id = data["id"]
new_data = data.drop("id", axis = 1)
new_data["id"] = copy_id
# new_data
# data

<>:2: SyntaxWarning: invalid escape sequence '\m'
<>:2: SyntaxWarning: invalid escape sequence '\m'
C:\Users\Asus\AppData\Local\Temp\ipykernel_3800\3120620778.py:2: SyntaxWarning: invalid escape sequence '\m'
  data = pd.read_csv("data\missingData.csv")

            name   age country   gender   income  id
0       John Doe  29.0     USA     Male  55000.0   1
1       John Doe  29.0     USA     Male  55000.0   1
2     Jane Smith   NaN  Canada   Female  62000.0   2
3           Alex   NaN     USA  Unknown  47000.0   3
4   Maria Garcia  34.0   Spain   Female      NaN   4
5         Li Wei  27.0   China     Male  51000.0   5
6            NaN  45.0   India   Female  73000.0   6
7     Ahmed Khan  38.0     NaN     Male  68000.0   7
8     Rachel Lee  29.0     USA   Female  62000.0   8
9    Carlos Ruiz   NaN  Mexico     Male  45000.0   9
10   Emily Davis  31.0     USA      NaN  58000.0  10

In [7]:
data[["gender","age"]].duplicated()

0     False
1      True
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
dtype: bool

In [ ]:
# data.drop_duplicates(inplace=True)   # COMPLETELY CHANGES ON THE ORIGINAL FILE

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [37]:
data

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [ ]:
data.dtypes  # check the all data types

# for changing the data types use as type function

id           int64
name           str
age        float64
country        str
gender         str
income     float64
dtype: object

#### Assignments

A. Display the following information:\
• First 10 rows\
• Shape & Data types\
• Summary statistics (mean, std, min, max)

B. Select only those rows where:\
• petal_length > 4.5\
• species = "Iris-virginica"

C. Group by species and compute:\
• Average sepal_length\
• Maximum petal_width\
• Standard deviation of sepal_width

In [2]:
import pandas as pd
data = pd.read_csv("data/IRIS.csv")

In [ ]:
# task 1 
data.head(10)
data.shape
# data.dtypes

data.describe()

       sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.054000      3.758667     1.198667
std        0.828066     0.433594      1.764420     0.763161
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [ ]:
# task 2
df = data[data["petal_length"] >4.5]   # using boolean filtering
df1 = data.query("petal_length > 4.5")   # using quey metod
iris = "Iris-virginica"
df2 = data.query("species == @iris")          # use @ and declare the string before comparng with a string
df2

In [36]:
# task 3    
# avg_sepal_length = data.groupby("species")["sepal_length"].mean()
std_sepal_width = data.groupby("species")["sepal_width"].std()
max_sepal_width = data.groupby("species")["sepal_width"].max()
# avg_sepal_length
max_sepal_width
std_sepal_width

species
Iris-setosa        0.381024
Iris-versicolor    0.313798
Iris-virginica     0.322497
Name: sepal_width, dtype: float64

##### D. Create a new column: \"petal_ratio" = petal_length / petal_width
• For each species, find the average petal_ratio.

In [38]:
data["petal_ratio"] = data["petal_length"] / data["petal_width"]

In [ ]:
# data["petal_res"] = data["petal_length"].apply(lambda x : x / data["petal_width"])  # apply function not working in place of ratio calculation

In [42]:
data = data.assign( 
    petal_res = data["petal_length"] / data["petal_width"] 
)

In [50]:
data = data.drop("petal_res",axis=1)

In [51]:
data

,sepal_length,sepal_width,petal_length,petal_width,species,petal_ratio
0,5.1,3.5,1.4,0.2,Iris-setosa,7.000000
1,4.9,3.0,1.4,0.2,Iris-setosa,7.000000
2,4.7,3.2,1.3,0.2,Iris-setosa,6.500000
3,4.6,3.1,1.5,0.2,Iris-setosa,7.500000
4,5.0,3.6,1.4,0.2,Iris-setosa,7.000000
...,...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,Iris-virginica,2.260870
146,6.3,2.5,5.0,1.9,Iris-virginica,2.631579
147,6.5,3.0,5.2,2.0,Iris-virginica,2.600000
148,6.2,3.4,5.4,2.3,Iris-virginica,2.347826
149,5.9,3.0,5.1,1.8,Iris-virginica,2.833333

Q2. Start by loading the TITANIC dataset. [Dataset Link: Titanic Dataset]\
A. Display only columns: Name, Sex, Age, Fare, Survived

In [52]:
import pandas as pd
data = pd.read_csv("data\Titanic-Dataset.csv")

<>:2: SyntaxWarning: invalid escape sequence '\T'
<>:2: SyntaxWarning: invalid escape sequence '\T'
C:\Users\Asus\AppData\Local\Temp\ipykernel_24332\3832093114.py:2: SyntaxWarning: invalid escape sequence '\T'
  data = pd.read_csv("data\Titanic-Dataset.csv")

In [56]:
data[["Name","Sex","Age","Fare","Survived"]]

,Name,Sex,Age,Fare,Survived
0,"Braund, Mr. Owen Harris",male,22.0,7.2500,0
1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,71.2833,1
2,"Heikkinen, Miss. Laina",female,26.0,7.9250,1
3,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,53.1000,1
4,"Allen, Mr. William Henry",male,35.0,8.0500,0
...,...,...,...,...,...
886,"Montvila, Rev. Juozas",male,27.0,13.0000,0
887,"Graham, Miss. Margaret Edith",female,19.0,30.0000,1
888,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,23.4500,0
889,"Behr, Mr. Karl Howell",male,26.0,30.0000,1
890,"Dooley, Mr. Patrick",male,32.0,7.7500,0

B. Select passengers who\
• Are female\
• Fare > 30

In [ ]:
females = data["Name"][data["Sex"] =="female"]     # boolean filtering

In [76]:
fare_g20 = data["Name"][data["Fare"]>20]

In [77]:
fare_g20

1      Cumings, Mrs. John Bradley (Florence Briggs Th...
3           Futrelle, Mrs. Jacques Heath (Lily May Peel)
6                                McCarthy, Mr. Timothy J
7                         Palsson, Master. Gosta Leonard
9                    Nasser, Mrs. Nicholas (Adele Achem)
                             ...
880         Shelley, Mrs. William (Imanita Parrish Hall)
885                 Rice, Mrs. William (Margaret Norton)
887                         Graham, Miss. Margaret Edith
888             Johnston, Miss. Catherine Helen "Carrie"
889                                Behr, Mr. Karl Howell
Name: Name, Length: 376, dtype: str

In [66]:
data

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

Group by and compute:\
C.Pclass\
•Survival rate\
•Average Fare\
•Average Age

In [87]:
survival_rate = data.groupby("Pclass")["Survived"].mean()
avg_Fare = data.groupby("Pclass")["Survived"].mean()
avg_Age = data.groupby("Pclass")["Survived"].mean()

Asignment completion

In [86]:
survival_rate

Pclass
1    0.629630
2    0.472826
3    0.242363
Name: Survived, dtype: float64